### ISSUE TITLE
后处理

### ISSUE THREAD

**Issue by long123524** [SonwYang/building-extraction#3]
您好，我想问一下您文章中提到的基于分水岭的后处理方法是怎么做的呢？看您的代码中似乎并没有用到这个方法？可以提供相关代码参考嘛？非常感谢

**Comment by SonwYang** [comment]
我刚刚上传了后处理的代码，你自己看看，主要就是两个输入（二值图，和归一化到0-255的强度图），一个参数x（0<x<255）,自己观察强度图，选择一个适中的值

**Comment by long123524** [comment]
非常感谢！我想问一下二值图是预测结果还是指标签图呢？

**Comment by SonwYang** [comment]
二值图为强度图的阈值分割结果或是概率分布图的通道维度上的argmax结果，如果是阈值分割的话，这个阈值A要比之前提到的阈值B要小。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonwYang/building-extraction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月27日(星期三) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonwYang/building-extraction] 后处理 (Issue #3)





 
非常感谢！我想问一下二值图是预测结果还是指标签图呢？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by long123524** [comment]
感谢您的答复！我尝试了去不断的调整阈值，发现不管怎么微调，结果但没有提升，反而变差了，比如下面这种情况，用了这种方法后，却多了裂缝（这是不应该存在的），还有其他的这种情况。您的后处理方法是不是有适用场景呢？比如小物体会好些，或者合适小幅图的预测？最后我想知道的是这里的后处理方法主要是为了解决什么问题呢？（物体粘连嘛？）期待您的答复
![image](https://user-images.githubusercontent.com/73996375/139169241-d0ecfa58-1c4a-4394-8df0-178db0963fac.png)

**Comment by SonwYang** [comment]
论文里面有详细叙述，其他与建筑相似的地类（具有固定的形态，内部纹理规律）你也可以套用。阈值的大小并不是盲目设定的，建议你仔细观察粘连部分的强度值，然后设定，祝你有个好的结果。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SonwYang/building-extraction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月28日(星期四) 上午9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SonwYang/building-extraction] 后处理 (Issue #3)





 
感谢您的答复！我尝试了去不断的调整阈值，发现不管怎么微调，结果但没有提升，反而变差了，比如下面这种情况，用了这种方法后，却多了裂缝（这是不应该存在的），还有其他的这种情况。您的后处理方法是不是有适用场景呢？比如小物体会好些，或者合适小幅图的预测？最后我想知道的是这里的后处理方法主要是为了解决什么问题呢？（物体粘连嘛？）期待您的答复
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
